### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by DavideSanvito** [progwriter/TMgen#1]
Hi,
I'm trying to create some traffic matrices with your module but I got an error when using modulated_gravity_tm.
All the other models (random_gravity_tm, gravity_tm, uniform_tm, exp_tm, spike_tm) work correctly.
This is my code

```
from tmgen import modulated_gravity_tm
tm = modulated_gravity_tm(num_nodes=2, num_tms=2, mean_traffic=1.0)
```

and this is the error

```
Traceback (most recent call last):
  File "/home/davide/PycharmProjects/robust-routing/data/tm_generator.py", line 11, in <module>
    tm = modulated_gravity_tm(num_nodes=2, num_tms=2, mean_traffic=1.0)
  File "src/tmgen/models.pyx", line 131, in tmgen.models.modulated_gravity_tm
  File "src/tmgen/models.pyx", line 182, in tmgen.models.modulated_gravity_tm
  File "src/tmgen/models.pyx", line 96, in tmgen.models._modulated_gravity
  File "src/tmgen/hmc.pyx", line 41, in tmgen.hmc.hmc_exact
ValueError: First dimension of f and g must match
```

Thanks!
Best,
Davide

**Comment by progwriter** [comment]
Hi Davide,
Apologies for the delay in my reply. 
I believe the issue has been resolved, feel free to give it a try.
If you find other issues, please feel free to report them. I am picking back up the maintenance of this project and anticipate response times will be shorter.

Best,
Victor

**Comment by DavideSanvito** [comment]
Thanks VIctor!
