### ISSUE TITLE
Cannot Install from pip

### ISSUE THREAD

**Issue by mattall** [progwriter/TMgen#6]
Hello, 

Thanks for writing this code. I want to use it but I'm not able to install it right now. I downloaded the repo. I also installed cython and numpy with pip.

I'm running python version 3.5.2 and pip 19.1.1.

Here is the error I am getting when I run `pip install -e .` or `pip install .`

```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Compiling src/tmgen/hmc.pyx because it changed.
    Compiling src/tmgen/models.pyx because it changed.
    Compiling src/tmgen/tm.pyx because it changed.
    [1/3] Cythonizing src/tmgen/hmc.pyx
    [2/3] Cythonizing src/tmgen/models.pyx
    [3/3] Cythonizing src/tmgen/tm.pyx
    /Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/TomNason/Dropbox/GreyLambda/GreyLambda_git/scripts/TMgen-master/src/tmgen/hmc.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    /Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/TomNason/Dropbox/GreyLambda/GreyLambda_git/scripts/TMgen-master/src/tmgen/models.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    /Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/TomNason/Dropbox/GreyLambda/GreyLambda_git/scripts/TMgen-master/src/tmgen/tm.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    Download error on https://pypi.python.org/simple/pytest-runner/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/TomNason/Dropbox/GreyLambda/GreyLambda_git/scripts/TMgen-master/setup.py", line 74, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules'
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/TomNason/GreyLambdaEnv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /Users/TomNason/Dropbox/GreyLambda/GreyLambda_git/scripts/TMgen-master/
```

**Comment by liuyi-thu** [comment]
You can try to run "pip install pytest-runner" before installing.
